Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/10/2023
Var
// Seção de Declarações das variáveis 
area, raio: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("digite o valor do raio do círculo")
leia (raio)
area<- pi*raio^2
escreval ("o valor da área é:",area)

Fimalgoritmo