Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/10/2023
Var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador <- 1
enquanto (contador <=10) faca
escreval ("Algorítmos é a melhor matéria do mundo!")
contador <- contador + 1
fimenquanto

Fimalgoritmo