Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/10/2023
Var
// Seção de Declarações das variáveis 
desconto, valor: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("digite o valor original do produto")
leia (valor)
desconto <- valor - (valor*(25/100))
escreval ("o valor com desconto será", desconto)

Fimalgoritmo