Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/10/2023
Var
// Seção de Declarações das variáveis 
x, a, b: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("digite um valor para A:")
LEIA (a)
escreval ("digite um valor para B:")
leia (b)
x<- a+b
se (x>10) entao
escreval (x)
senao
escreval (x+5)
fimse

Fimalgoritmo