Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/10/2023
Var
// Seção de Declarações das variáveis 
numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Digite um número real")
leia (numero)

se (numero mod 2=0) entao
escreval ("Seu numero é par")
senao
escreval ("Seu número é ímpar")
fimse
Fimalgoritmo