Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/10/2023
Var
// Seção de Declarações das variáveis 
n, i: inteiro
soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i <- 1
n <- 2
soma <- n

enquanto (n <= 20) faca
n <- n+1
soma <- soma+n

escreval (soma)
fimenquanto


Fimalgoritmo