Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/10/2023
Var
// Seção de Declarações das variáveis 
numerospares: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para numerospares de 0 ate 20 passo 2  faca
escreval (numerospares)
fimpara
Fimalgoritmo